---
- name: Deploy Flask App
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Pull Docker Image
      docker_image:
        name: kemiye01/flask-app:v1
        state: present

    - name: Start Docker Container
      docker_container:
        name: flaskapp
        image: kemiye01/flask-app:v1
        ports:
          - "5000:5000"
        state: started