---
- name: Install Docker and run container
  hosts: all
  become: true
  
  vars:
    ansible_become: yes
    docker_image_name: chibuzo199/Flaskapp:M1
    docker_container_name: faskapp
    # python_interpreter: /usr/bin/python3
    container_default_behavior: compatibility
  
  tasks:
     
    - name: Install python3
      apt:
        name: python3
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: install docker-py
      pip:
        name: docker-py
        state: present            
    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: start docker
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: chibuzo199/Flaskapp:M1
        source: pull

    # - name: Pull Docker Image
    #   become: yes
    #   docker_image:
    #     name: chibuzo199/Flaskapp:M1
    #     state: present

    - name: Start Docker Container
      docker_container:
        name: Flaskapp
        image: chibuzo199/Flaskapp:M1
        ports:
          - 5000:5000
        state: started