---
- name: Install Docker and run container
  hosts: all
  become: true
  
  vars:
    docker_image_name: kemiye01/flask-app:v3
    docker_container_name: myfaskapp
    python_interpreter: /usr/bin/python3
  
  tasks:
     
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
    # Install Docker
    - name: Install Docker
      apt:
        name: python3-docker
        state: latest

    - name: start docker
      service:
        name: docker
        state: started
    
    # Pull Docker image
    - name: Pull Docker image
      docker_image:
        name: kemiye01/flask-app:v3
    
    # Run Docker container
    - name: Run Docker container
      become: yes
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart: yes
        tty: yes
        interactive: yes
        command: "{{ python_interpreter }}"
