---
- name: Install Docker and run container
  hosts: all
  become: true
  
  vars:
    ansible_become: yes
    docker_image_name: kemiye01/flask-app:v3
    docker_container_name: myfaskapp
    python_interpreter: /usr/bin/python3
    container_default_behavior: compatibility
  
  tasks:
     
    - name: Install required packages
      apt:
        name: python3
        state: present

    - name: install pip
      apt:
        name: python3-pip
        state: present

    - name: install pip
      pip:
        name: docker-py
        state: present            
    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: start docker
      service:
        name: docker
        state: started
    
    # Pull Docker image
    - name: Pull Docker image
      docker_image:
        name: kemiye01/flask-app:v3
    
    # Run Docker container
    - name: Run Docker container
      become: yes
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart: yes
        tty: yes
        interactive: yes
        command: "{{ python_interpreter }}"
